[package]
name = "mmh3"
default-run = "mmh3"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
webm = ["mmh3-output/webm"]
cuda = ["dep:mmh3-cuda"]
mp4 = ["cuda", "dep:mmh3-output-nvenc", "mmh3-output/mp4"]

[dependencies]
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
mmh3-core = { path = "crates/mmh3-core" }
mmh3-output = { path = "crates/mmh3-output", default-features = false }
mmh3-cuda = { path = "crates/mmh3-cuda", optional = true }
mmh3-output-nvenc = { path = "crates/mmh3-output-nvenc", optional = true }

[workspace]
members = ["crates/mmh3-core", "crates/mmh3-cpu", "crates/mmh3-cuda", "crates/mmh3-output", "crates/mmh3-output-nvenc"]
default-members = [".", "crates/mmh3-core", "crates/mmh3-cpu", "crates/mmh3-output"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
