[package]
name = "mmh3"
default-run = "mmh3"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
cuda = ["dep:mmh3-cuda"]

[dependencies]
mmh3-core = { path = "crates/mmh3-core" }
mmh3-cuda = { path = "crates/mmh3-cuda", optional = true }

[workspace]
members = ["crates/mmh3-core", "crates/mmh3-cpu", "crates/mmh3-cuda"]
default-members = [".", "crates/mmh3-core", "crates/mmh3-cpu"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
