//! The byte-level BPE tokenizer of Qwen2 and Qwen3, with the merges of the Qwen3-VL tokenizer built
//! in.
//!
//! Encoding splits the text on added tokens, applies NFC to the rest, splits it with the Qwen2
//! pre-tokenizer, maps every byte to its printable stand-in and merges the pieces by rank. No
//! special tokens are added around the text.

mod pretokenize;
mod unicode;
// Generated by tools/unicode/generate_tables.py, which lays out the table rows.
#[rustfmt::skip]
mod unicode_tables;

pub use pretokenize::pretokenize;
pub use unicode::{is_letter, nfc};

use std::collections::HashMap;

/// The merges of the Qwen3-VL tokenizer, one pair per line in rank order.
const QWEN_MERGES: &str = include_str!("merges.txt");

/// The added tokens of the Qwen3 tokenizer, whose ids follow the BPE vocabulary from
/// [`QWEN_FIRST_ADDED_ID`].
const QWEN_ADDED_TOKENS: [&str; 26] = [
    "<|endoftext|>",
    "<|im_start|>",
    "<|im_end|>",
    "<|object_ref_start|>",
    "<|object_ref_end|>",
    "<|box_start|>",
    "<|box_end|>",
    "<|quad_start|>",
    "<|quad_end|>",
    "<|vision_start|>",
    "<|vision_end|>",
    "<|vision_pad|>",
    "<|image_pad|>",
    "<|video_pad|>",
    "<tool_call>",
    "</tool_call>",
    "<|fim_prefix|>",
    "<|fim_middle|>",
    "<|fim_suffix|>",
    "<|fim_pad|>",
    "<|repo_name|>",
    "<|file_sep|>",
    "<tool_response>",
    "</tool_response>",
    "<think>",
    "</think>",
];
const QWEN_FIRST_ADDED_ID: u32 = 151_643;

/// Tokens MiniMax H3 adds to the Qwen3 vocabulary, with the ids of the released tokenizer.
pub const H3_EXTRA_TOKENS: [(&str, u32); 7] = [
    ("<d>", 151_669),
    ("</d>", 151_670),
    ("<|cutoff|>", 151_671),
    ("<|lyrics_start|>", 151_672),
    ("<|lyrics_end|>", 151_673),
    ("<|caption_start|>", 151_674),
    ("<|caption_end|>", 151_675),
];

/// GPT-2's printable stand-ins for the 256 byte values.
fn byte_characters() -> [char; 256] {
    let mut characters = ['\0'; 256];
    let mut next = 256;
    for byte in 0..256u32 {
        let printable = (33..=126).contains(&byte)
            || (161..=172).contains(&byte)
            || (174..=255).contains(&byte);
        characters[byte as usize] = if printable {
            char::from_u32(byte).unwrap()
        } else {
            next += 1;
            char::from_u32(next - 1).unwrap()
        };
    }
    characters
}

pub struct Tokenizer {
    vocabulary: HashMap<String, u32>,
    /// Token text by id, byte-level for the BPE vocabulary and verbatim for added tokens.
    tokens: HashMap<u32, String>,
    /// Rank and merged id of each mergeable pair of ids.
    merges: HashMap<(u32, u32), (u32, u32)>,
    /// Added tokens, matched verbatim in the input before normalization.
    added: Vec<(String, u32)>,
    byte_tokens: [u32; 256],
    character_bytes: HashMap<char, u8>,
}

impl Tokenizer {
    /// The MiniMax H3 tokenizer: the Qwen3 tokenizer plus [`H3_EXTRA_TOKENS`].
    pub fn h3() -> Self {
        let mut tokenizer =
            Self::from_merges(QWEN_MERGES).expect("the built-in merges form a vocabulary");
        for (index, content) in QWEN_ADDED_TOKENS.into_iter().enumerate() {
            tokenizer.add_token(content, QWEN_FIRST_ADDED_ID + index as u32);
        }
        for (content, id) in H3_EXTRA_TOKENS {
            tokenizer.add_token(content, id);
        }
        tokenizer
    }

    /// A byte-level BPE from its merges, one pair per line in rank order. The 256 byte tokens take
    /// the ids 0 to 255 in the order of their printable stand-ins, and each merge adds the next id,
    /// as in the GPT-2 and Qwen vocabularies.
    fn from_merges(text: &str) -> Result<Self, String> {
        let characters = byte_characters();
        let mut stand_ins = characters;
        stand_ins.sort_unstable();
        let mut vocabulary: HashMap<String, u32> = stand_ins
            .iter()
            .enumerate()
            .map(|(id, character)| (character.to_string(), id as u32))
            .collect();

        let mut merges = HashMap::new();
        for (rank, line) in text.lines().enumerate() {
            let (left, right) = line
                .split_once(' ')
                .ok_or_else(|| format!("merge {rank} is not a pair"))?;
            let id = |token: &str| {
                vocabulary.get(token).copied().ok_or_else(|| {
                    format!("merge {rank} joins {token:?}, which is not a token yet")
                })
            };
            let pair = (id(left)?, id(right)?);
            let token = format!("{left}{right}");
            if vocabulary.contains_key(&token) {
                return Err(format!("merge {rank} makes {token:?} again"));
            }
            let merged = vocabulary.len() as u32;
            vocabulary.insert(token, merged);
            merges.insert(pair, (rank as u32, merged));
        }
        let tokens = vocabulary
            .iter()
            .map(|(token, &id)| (id, token.clone()))
            .collect();

        let byte_tokens = characters.map(|character| vocabulary[&character.to_string()]);
        let character_bytes = characters
            .iter()
            .enumerate()
            .map(|(byte, &character)| (character, byte as u8))
            .collect();
        Ok(Tokenizer {
            vocabulary,
            tokens,
            merges,
            added: Vec::new(),
            byte_tokens,
            character_bytes,
        })
    }

    /// Adds a token that is matched verbatim in the input, like the special tokens of the Qwen
    /// tokenizer.
    pub fn add_token(&mut self, content: &str, id: u32) {
        self.added.retain(|(existing, _)| existing != content);
        self.added.push((content.to_owned(), id));
        self.tokens.insert(id, content.to_owned());
    }

    pub fn token_id(&self, token: &str) -> Option<u32> {
        self.added
            .iter()
            .find(|(content, _)| content == token)
            .map(|&(_, id)| id)
            .or_else(|| self.vocabulary.get(token).copied())
    }

    /// The leftmost, then longest, added token in `text`, as its byte offset, length and id.
    fn next_added(&self, text: &str) -> Option<(usize, usize, u32)> {
        let mut best: Option<(usize, usize, u32)> = None;
        for (content, id) in &self.added {
            if let Some(offset) = text.find(content.as_str()) {
                let better = match best {
                    None => true,
                    Some((best_offset, best_length, _)) => {
                        offset < best_offset
                            || (offset == best_offset && content.len() > best_length)
                    }
                };
                if better {
                    best = Some((offset, content.len(), *id));
                }
            }
        }
        best
    }

    fn encode_piece(&self, piece: &str, output: &mut Vec<u32>) {
        let mut symbols: Vec<u32> = piece
            .bytes()
            .map(|byte| self.byte_tokens[byte as usize])
            .collect();
        loop {
            let best = symbols
                .windows(2)
                .filter_map(|pair| {
                    self.merges
                        .get(&(pair[0], pair[1]))
                        .map(|&(rank, merged)| (rank, (pair[0], pair[1]), merged))
                })
                .min_by_key(|&(rank, _, _)| rank);
            let Some((_, (left, right), merged)) = best else {
                break;
            };
            let mut merged_symbols = Vec::with_capacity(symbols.len());
            let mut index = 0;
            while index < symbols.len() {
                if index + 1 < symbols.len()
                    && symbols[index] == left
                    && symbols[index + 1] == right
                {
                    merged_symbols.push(merged);
                    index += 2;
                } else {
                    merged_symbols.push(symbols[index]);
                    index += 1;
                }
            }
            symbols = merged_symbols;
        }
        output.extend(symbols);
    }

    pub fn encode(&self, text: &str) -> Vec<u32> {
        let mut ids = Vec::new();
        let mut rest = text;
        while !rest.is_empty() {
            let (segment, added) = match self.next_added(rest) {
                Some((offset, length, id)) => {
                    let segment = &rest[..offset];
                    rest = &rest[offset + length..];
                    (segment, Some(id))
                }
                None => (std::mem::take(&mut rest), None),
            };
            for piece in pretokenize(&nfc(segment)) {
                self.encode_piece(&piece, &mut ids);
            }
            ids.extend(added);
        }
        ids
    }

    pub fn decode(&self, ids: &[u32]) -> String {
        let mut bytes = Vec::new();
        for id in ids {
            let Some(token) = self.tokens.get(id) else {
                continue;
            };
            if self.added.iter().any(|&(_, added)| added == *id) {
                bytes.extend_from_slice(token.as_bytes());
            } else {
                bytes.extend(
                    token
                        .chars()
                        .filter_map(|character| self.character_bytes.get(&character)),
                );
            }
        }
        String::from_utf8_lossy(&bytes).into_owned()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The 256 byte tokens plus "ab", "abc" and " a", in the order of their merges, and the added
    /// token "<|x|>".
    fn tiny_tokenizer() -> Tokenizer {
        let space = byte_characters()[b' ' as usize];
        let mut tokenizer = Tokenizer::from_merges(&format!("a b\nab c\n{space} a\n")).unwrap();
        tokenizer.add_token("<|x|>", 300);
        tokenizer
    }

    #[test]
    fn merges_by_rank_and_splits_added_tokens() {
        let tokenizer = tiny_tokenizer();
        let byte = |value: u8| tokenizer.byte_tokens[value as usize];
        assert_eq!(tokenizer.encode("abc"), [257]);
        assert_eq!(tokenizer.encode("abab"), [256, 256]);
        assert_eq!(tokenizer.encode("x ac"), [byte(b'x'), 258, byte(b'c')]);
        assert_eq!(tokenizer.encode("x abc"), [byte(b'x'), byte(b' '), 257]);
        assert_eq!(tokenizer.encode("ab<|x|>c"), [256, 300, byte(b'c')]);
        assert_eq!(
            tokenizer.decode(&tokenizer.encode("x abc<|x|>é")),
            "x abc<|x|>é"
        );
    }

    #[test]
    fn numbers_bytes_like_gpt2() {
        let tokenizer = tiny_tokenizer();
        assert_eq!(
            (
                tokenizer.byte_tokens[b'!' as usize],
                tokenizer.byte_tokens[0],
                tokenizer.byte_tokens[b' ' as usize]
            ),
            (0, 188, 220)
        );
    }

    #[test]
    fn rejects_merges_of_unknown_tokens() {
        assert!(Tokenizer::from_merges("ab c\n").is_err());
        assert!(Tokenizer::from_merges("a b\na b\n").is_err());
    }
}
