"""Generates the Unicode tables of the tokenizer from Python's unicodedata.

    python3 tools/unicode/generate_tables.py \\
        > crates/mmh3-core/src/tokenizer/unicode_tables.rs

The tables cover what the Qwen2 pre-tokenizer and NFC need: the letters of general
category L, the canonical combining classes, the canonical decompositions and the
primary composites. Hangul syllables are left to the algorithmic rules.
"""

import sys
import unicodedata

CODE_POINTS = range(0x110000)
# Every code point below this bound is NFC-stable and never takes part in a composition
# as the second code point.
NFC_STABLE_BELOW = 0x300


def is_hangul_syllable(code_point):
    return 0xAC00 <= code_point <= 0xD7A3


def is_surrogate(code_point):
    return 0xD800 <= code_point <= 0xDFFF


def ranges(code_points):
    result = []
    for code_point in code_points:
        if result and result[-1][1] == code_point - 1:
            result[-1][1] = code_point
        else:
            result.append([code_point, code_point])
    return result


def emit(name, comment, entries, per_line):
    print(f"/// {comment}")
    print(f"pub(super) const {name}: &[{entries[0][0]}] = &[")
    rows = [entry[1] for entry in entries]
    for start in range(0, len(rows), per_line):
        print("    " + " ".join(rows[start : start + per_line]))
    print("];")
    print()


def main():
    letters = ranges(
        code_point
        for code_point in CODE_POINTS
        if not is_surrogate(code_point)
        and unicodedata.category(chr(code_point)).startswith("L")
    )

    classes = []
    for code_point in CODE_POINTS:
        if is_surrogate(code_point):
            continue
        combining = unicodedata.combining(chr(code_point))
        if combining == 0:
            continue
        if classes and classes[-1][1] == code_point - 1 and classes[-1][2] == combining:
            classes[-1][1] = code_point
        else:
            classes.append([code_point, code_point, combining])

    decompositions = []
    compositions = []
    for code_point in CODE_POINTS:
        if is_surrogate(code_point) or is_hangul_syllable(code_point):
            continue
        mapping = unicodedata.decomposition(chr(code_point))
        if not mapping or mapping.startswith("<"):
            continue
        parts = [int(part, 16) for part in mapping.split()]
        assert len(parts) <= 2, hex(code_point)
        first, second = parts[0], parts[1] if len(parts) == 2 else 0
        decompositions.append((code_point, first, second))
        if second and unicodedata.normalize("NFC", chr(code_point)) == chr(code_point):
            compositions.append((first, second, code_point))
    compositions.sort()

    for code_point in range(NFC_STABLE_BELOW):
        assert unicodedata.normalize("NFC", chr(code_point)) == chr(code_point), hex(
            code_point
        )
        assert unicodedata.combining(chr(code_point)) == 0, hex(code_point)
    assert all(second >= NFC_STABLE_BELOW for _, second, _ in compositions)

    print(
        f"//! Generated by tools/unicode/generate_tables.py from Unicode {unicodedata.unidata_version}. Do not edit."
    )
    print()
    print(
        "/// Code points below this bound are NFC-stable and are never the second code point of a composition."
    )
    print(f"pub(super) const NFC_STABLE_BELOW: u32 = 0x{NFC_STABLE_BELOW:X};")
    print()
    emit(
        "LETTERS",
        "Inclusive ranges of general category L, sorted.",
        [("(u32, u32)", f"(0x{start:X}, 0x{end:X}),") for start, end in letters],
        6,
    )
    emit(
        "COMBINING_CLASSES",
        "Inclusive ranges with a non-zero canonical combining class, sorted.",
        [
            ("(u32, u32, u8)", f"(0x{start:X}, 0x{end:X}, {combining}),")
            for start, end, combining in classes
        ],
        5,
    )
    emit(
        "DECOMPOSITIONS",
        "Canonical decompositions by code point: the first and second code points, second 0 for singletons.",
        [
            ("(u32, u32, u32)", f"(0x{code_point:X}, 0x{first:X}, 0x{second:X}),")
            for code_point, first, second in decompositions
        ],
        4,
    )
    emit(
        "COMPOSITIONS",
        "Primary composites by their first and second code points, sorted.",
        [
            ("(u32, u32, u32)", f"(0x{first:X}, 0x{second:X}, 0x{code_point:X}),")
            for first, second, code_point in compositions
        ],
        4,
    )
    print(
        f"generated {len(letters)} letter ranges, {len(classes)} class ranges, {len(decompositions)} "
        f"decompositions and {len(compositions)} compositions",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
